import { ImageSourcePropType } from 'react-native';

export const ENEMY_IMAGES: Record<string, ImageSourcePropType> = {
  skeleton:         require('../assets/dungeon/skeleton.webp'),
  orc:              require('../assets/dungeon/orc.webp'),
  troll:            require('../assets/dungeon/troll.webp'),
  slime:            require('../assets/dungeon/slime.webp'),
  goblin:           require('../assets/dungeon/goblin.webp'),
  'dark mage':      require('../assets/dungeon/dark-mage.webp'),
  'mushroom golem': require('../assets/dungeon/goblin.webp'),
  'bandit chief':   require('../assets/dungeon/orc.webp'),
  'ice witch':      require('../assets/dungeon/dark-mage.webp'),
  'fire imp':       require('../assets/dungeon/slime.webp'),
  'lava titan':     require('../assets/dungeon/troll.webp'),
  banshee:          require('../assets/dungeon/dark-mage.webp'),
  'shadow knight':  require('../assets/dungeon/skeleton.webp'),
  'mummy lord':     require('../assets/dungeon/skeleton.webp'),
  wyvern:           require('../assets/dungeon/troll.webp'),
  'void lich':      require('../assets/dungeon/dark-mage.webp'),
  'shadow wolf':    require('../assets/dungeon/skeleton.webp'),
  'thunder eagle':  require('../assets/dungeon/goblin.webp'),
  'frost golem':    require('../assets/dungeon/troll.webp'),
  'fire salamander':require('../assets/dungeon/slime.webp'),
  'demon warlord':  require('../assets/dungeon/orc.webp'),
  'shade specter':  require('../assets/dungeon/dark-mage.webp'),
  'stone colossus': require('../assets/dungeon/troll.webp'),
  'void crawler':   require('../assets/dungeon/slime.webp'),
  'fallen paladin': require('../assets/dungeon/skeleton.webp'),
  'cursed knight':  require('../assets/dungeon/skeleton.webp'),
  'stone titan':    require('../assets/dungeon/troll.webp'),
  'inferno djinn':  require('../assets/dungeon/dark-mage.webp'),
  'void archon':    require('../assets/dungeon/dark-mage.webp'),
  'ancient dragon': require('../assets/dungeon/orc.webp'),
};
